/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProofRouteImport } from './routes/_authed.proof'
import { Route as AuthedAccountRouteImport } from './routes/_authed.account'
import { Route as AuthedAccountIndexRouteImport } from './routes/_authed.account.index'
import { Route as AuthedAccountArchiveRouteImport } from './routes/_authed.account.archive'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProofRoute = AuthedProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountIndexRoute = AuthedAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAccountRoute,
} as any)
const AuthedAccountArchiveRoute = AuthedAccountArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthedAccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AuthedAccountRouteWithChildren
  '/proof': typeof AuthedProofRoute
  '/account/archive': typeof AuthedAccountArchiveRoute
  '/account/': typeof AuthedAccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proof': typeof AuthedProofRoute
  '/account/archive': typeof AuthedAccountArchiveRoute
  '/account': typeof AuthedAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/account': typeof AuthedAccountRouteWithChildren
  '/_authed/proof': typeof AuthedProofRoute
  '/_authed/account/archive': typeof AuthedAccountArchiveRoute
  '/_authed/account/': typeof AuthedAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/proof' | '/account/archive' | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/proof' | '/account/archive' | '/account'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/account'
    | '/_authed/proof'
    | '/_authed/account/archive'
    | '/_authed/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/proof': {
      id: '/_authed/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof AuthedProofRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/': {
      id: '/_authed/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthedAccountIndexRouteImport
      parentRoute: typeof AuthedAccountRoute
    }
    '/_authed/account/archive': {
      id: '/_authed/account/archive'
      path: '/archive'
      fullPath: '/account/archive'
      preLoaderRoute: typeof AuthedAccountArchiveRouteImport
      parentRoute: typeof AuthedAccountRoute
    }
  }
}

interface AuthedAccountRouteChildren {
  AuthedAccountArchiveRoute: typeof AuthedAccountArchiveRoute
  AuthedAccountIndexRoute: typeof AuthedAccountIndexRoute
}

const AuthedAccountRouteChildren: AuthedAccountRouteChildren = {
  AuthedAccountArchiveRoute: AuthedAccountArchiveRoute,
  AuthedAccountIndexRoute: AuthedAccountIndexRoute,
}

const AuthedAccountRouteWithChildren = AuthedAccountRoute._addFileChildren(
  AuthedAccountRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRouteWithChildren
  AuthedProofRoute: typeof AuthedProofRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRouteWithChildren,
  AuthedProofRoute: AuthedProofRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
