/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedPlayRouteImport } from './routes/_authed.play'
import { Route as AuthedAccountRouteImport } from './routes/_authed.account'
import { Route as AuthedAccountIndexRouteImport } from './routes/_authed.account.index'
import { Route as AuthedAccountSavesRouteImport } from './routes/_authed.account.saves'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPlayRoute = AuthedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountIndexRoute = AuthedAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAccountRoute,
} as any)
const AuthedAccountSavesRoute = AuthedAccountSavesRouteImport.update({
  id: '/saves',
  path: '/saves',
  getParentRoute: () => AuthedAccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AuthedAccountRouteWithChildren
  '/play': typeof AuthedPlayRoute
  '/account/saves': typeof AuthedAccountSavesRoute
  '/account/': typeof AuthedAccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play': typeof AuthedPlayRoute
  '/account/saves': typeof AuthedAccountSavesRoute
  '/account': typeof AuthedAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/account': typeof AuthedAccountRouteWithChildren
  '/_authed/play': typeof AuthedPlayRoute
  '/_authed/account/saves': typeof AuthedAccountSavesRoute
  '/_authed/account/': typeof AuthedAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/play' | '/account/saves' | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play' | '/account/saves' | '/account'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/account'
    | '/_authed/play'
    | '/_authed/account/saves'
    | '/_authed/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/play': {
      id: '/_authed/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthedPlayRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/': {
      id: '/_authed/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthedAccountIndexRouteImport
      parentRoute: typeof AuthedAccountRoute
    }
    '/_authed/account/saves': {
      id: '/_authed/account/saves'
      path: '/saves'
      fullPath: '/account/saves'
      preLoaderRoute: typeof AuthedAccountSavesRouteImport
      parentRoute: typeof AuthedAccountRoute
    }
  }
}

interface AuthedAccountRouteChildren {
  AuthedAccountSavesRoute: typeof AuthedAccountSavesRoute
  AuthedAccountIndexRoute: typeof AuthedAccountIndexRoute
}

const AuthedAccountRouteChildren: AuthedAccountRouteChildren = {
  AuthedAccountSavesRoute: AuthedAccountSavesRoute,
  AuthedAccountIndexRoute: AuthedAccountIndexRoute,
}

const AuthedAccountRouteWithChildren = AuthedAccountRoute._addFileChildren(
  AuthedAccountRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRouteWithChildren
  AuthedPlayRoute: typeof AuthedPlayRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRouteWithChildren,
  AuthedPlayRoute: AuthedPlayRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
